設定画面を動くようにする
teichaku-org/teichaku pull request #1
Opened 2022-12-17 15:54 UTC by web3rakko

こんばんは。
すみません、結構時間が空いてしまったのですが、以下の課題について取り急ぎDAOトークンの設定欄についてコントラクトを呼び出すようにしました。
https://trello.com/c/DZdJQo5K/15-%E8%A8%AD%E5%AE%9A%E7%94%BB%E9%9D%A2%E3%82%92%E5%8B%95%E3%81%8F%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B

このような形で大丈夫でしょうか。
もし、問題ないようでしたら他の設定欄についても順次進めていきます。
少し考えたのですが、バリデーションの追加などは別課題で行う形になりますでしょうか。

また、トークン設定機能についてUSDCのスマートコントラクトのアドレスでテストを行いまして、
mainnetからフォークし、ローカルでblockchainを起動することについて``README.md``に追加したのですが、
こちらについてもご確認いただけますでしょうか。

よろしくお願いいたします。

2022-12-18 08:40 UTC, KitaharaMugiro requested changes

2022-12-18 08:40 UTC, KitaharaMugiro commented on README.md
> +
こんなことできるんですね！

2022-12-18 08:40 UTC, KitaharaMugiro commented on contracts/Poll.sol
> +
setTokenAddressで同様のことができるので、そちらでやるようにしたいです！

2022-12-18 08:40 UTC, KitaharaMugiro commented on frontend/src/components/setting/TokenSetting.tsx
> +    console.log(form.values.tokenAddress)
コントラアクトアドレスかどうかだけはバリデーションした方が良いかと思います！
frontend/src/components/create-dao/SetReward.tsx の実装が参考になるかと思います

2022-12-18 11:43 UTC, web3rakko commented on contracts/Poll.sol
> +
承知しました、setTokenAddressにします！

2022-12-18 11:44 UTC, web3rakko commented on frontend/src/components/setting/TokenSetting.tsx
> +    console.log(form.values.tokenAddress)
ありがとうございます、SetReward.tsxを参考にさせていただきます！

2022-12-22 15:54 UTC, web3rakko commented
@KitaharaMugiro 
こんばんは。
すみません、こちらについて少し考えたのですが、SBTアドレスの設定機能も設定画面の下部の方にあるかと思います。
SBTのアドレスが設定されている状態でDAOトークンの設定機能でSBTのアドレスにゼロアドレスが設定されてしまうとそれまで登録されていたSBTのアドレスがゼロアドレスとなり、問題があるかと考えたのですが如何でしょうか？

2022-12-23 01:13 UTC, KitaharaMugiro commented
> @KitaharaMugiro こんばんは。 すみません、こちらについて少し考えたのですが、SBTアドレスの設定機能も設定画面の下部の方にあるかと思います。 SBTのアドレスが設定されている状態でDAOトークンの設定機能でSBTのアドレスにゼロアドレスが設定されてしまうとそれまで登録されていたSBTのアドレスがゼロアドレスとなり、問題があるかと考えたのですが如何でしょうか？

ありがとうございます！
確かにそうですね。。
現在設定されているSBTアドレスをフロントで取得して、設定するときに送り込むのはいかがでしょうか？
もしSBTアドレスがなければゼロアドレスで埋めるみたいな

2022-12-23 11:54 UTC, web3rakko commented
> 現在設定されているSBTアドレスをフロントで取得して、設定するときに送り込むのはいかがでしょうか？
> もしSBTアドレスがなければゼロアドレスで埋めるみたいな

ありがとうございます、承知いたしました！
こちらの方針で進めさせて頂こうと思います。

2023-01-01 16:26 UTC, web3rakko commented
@KitaharaMugiro 
こんばんは。
取り急ぎ「報酬に用いるトークン」と「レビューに必要なSBT」の項目についてバリデーションを追加したのですが、このような形式で問題ないでしょうか。
ライブラリにバリデーションの機能があったので、chenさんのものを参考にさせていただき、それらの機能を使いバリデーションを追加しました。

2023-01-02 04:24 UTC, KitaharaMugiro commented
@web3rakko ありがとうございます！ 確認してみますね

2023-01-02 04:26 UTC, KitaharaMugiro commented
とてもいいと思います！ こちらマージしても大丈夫ですか？

2023-01-02 09:08 UTC, web3rakko commented
@KitaharaMugiro 
ご確認ありがとうございます！

> こちらマージしても大丈夫ですか？
念の為の確認なのですが、DAOトークンとDAO NFTの設定画面のみ現在対応しており、
他の設定機能については未だなのですが、大丈夫そうでしょうか？

ただ私としてはマージについては大丈夫です！

2023-01-06 03:03 UTC, merged